
name: Build Android and iOS

on: [push, pull_request]

jobs:
        
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Android
      run: |
        nuget restore
        cd Droid
        msbuild qController.Droid.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug  
  iOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: iOS
      run: |
        cd Blank
        nuget restore
        cd iOS
        msbuild qController.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Debug        
